'use client';

import { useEffect, useState } from 'react';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { deleteAccount, exportAccount, getSettings, logout, mockLogin, updateSettings } from '@/lib/api';
import type { UserSettings } from '@/types/settings';

const defaults: UserSettings = {
  preferred_language: 'English',
  response_style: 'balanced',
  crisis_region: 'United States',
  save_journal_history: true,
  save_mood_history: true,
  ai_provider: 'mock',
  enable_real_ai: false,
  openai_api_key: '',
  openai_model: 'gpt-4o-mini',
  openai_base_url: '',
  openrouter_api_key: '',
  openrouter_model: 'openai/gpt-4o-mini',
  openrouter_base_url: 'https://openrouter.ai/api/v1',
  hf_token: '',
  hf_model: '',
  hf_base_url: '',
};

export default function Page() {
  const [settings, setSettings] = useState<UserSettings>(defaults);
  const [status, setStatus] = useState('Loading saved settings...');
  const [showHFToken, setShowHFToken] = useState(false);
  const [showOpenAIKey, setShowOpenAIKey] = useState(false);
  const [showOpenRouterKey, setShowOpenRouterKey] = useState(false);

  useEffect(() => {
    async function load() {
      try {
        const loaded = await getSettings();
        setSettings({ ...defaults, ...loaded });
        setStatus('Settings loaded from persistent storage.');
      } catch {
        setStatus('Please log in or use demo login to load settings.');
      }
    }
    void load();
  }, []);

  async function startDemoSession() {
    try {
      const auth = await mockLogin();
      const loaded = await getSettings();
      setSettings({ ...defaults, ...loaded });
      setStatus('Demo login active. Settings loaded from persistent storage.');
    } catch {
      setStatus('Could not start demo login.');
    }
  }

  async function save() {
    try {
      const saved = await updateSettings(settings);
      setSettings({ ...defaults, ...saved });
      setStatus('Settings saved for the current user.');
    } catch {
      setStatus('Please log in or use demo login before saving settings.');
    }
  }

  async function downloadExport() {
    try {
      await exportAccount();
      setStatus('Account export generated by the backend.');
    } catch {
      setStatus('Please log in before exporting account data.');
    }
  }

  async function signOut() {
    await logout();
    setStatus('Logged out. Protected data is unavailable until you log in again.');
  }

  async function requestDelete() {
    try {
      await deleteAccount();
      setStatus('Account marked for deletion and login disabled.');
    } catch {
      setStatus('Please log in before deleting account data.');
    }
  }

  return (
    <section className="space-y-8 animate-fade-in">
      <div>
        <p className="text-xs font-bold uppercase tracking-widest text-calm font-outfit">Configuration</p>
        <h1 className="text-4xl font-extrabold tracking-tight text-ocean sm:text-5xl font-outfit mt-1">Settings</h1>
        <p className="mt-3 max-w-2xl text-base text-slate-600">Manage preferences, saved data choices, and regional safety resources.</p>
      </div>

      <div className="grid gap-6 lg:grid-cols-[1.1fr_0.9fr] items-start">
        <div className="space-y-6">
          {/* General Preferences Group */}
          <Card title="General Preferences">
            <div className="grid gap-5 sm:grid-cols-2">
              <div className="space-y-2">
                <label className="block text-xs font-bold uppercase tracking-wider text-calm font-outfit" htmlFor="preferred-language">
                  Preferred language
                </label>
                <select
                  id="preferred-language"
                  value={settings.preferred_language}
                  onChange={(event) => setSettings({ ...settings, preferred_language: event.target.value })}
                  className="w-full rounded-xl border border-slate-200 bg-white/50 px-4 py-3 text-slate-800 focus:outline-none focus:ring-2 focus:ring-calm/15 focus:border-calm transition-all duration-300 font-medium text-sm hover:border-slate-300 shadow-sm cursor-pointer"
                >
                  {['English', 'Arabic', 'Both'].map((option) => (
                    <option key={option} className="bg-white text-slate-800">{option}</option>
                  ))}
                </select>
              </div>

              <div className="space-y-2">
                <label className="block text-xs font-bold uppercase tracking-wider text-calm font-outfit" htmlFor="response-style">
                  Response style
                </label>
                <select
                  id="response-style"
                  value={settings.response_style}
                  onChange={(event) => setSettings({ ...settings, response_style: event.target.value })}
                  className="w-full rounded-xl border border-slate-200 bg-white/50 px-4 py-3 text-slate-800 focus:outline-none focus:ring-2 focus:ring-calm/15 focus:border-calm transition-all duration-300 font-medium text-sm hover:border-slate-300 shadow-sm cursor-pointer"
                >
                  {['short', 'balanced', 'detailed'].map((option) => (
                    <option key={option} className="bg-white text-slate-800">{option}</option>
                  ))}
                </select>
              </div>
            </div>
          </Card>

          {/* Privacy & Safety Group */}
          <Card title="Privacy & Regional Safety">
            <div className="space-y-5">
              <div className="space-y-2">
                <label className="block text-xs font-bold uppercase tracking-wider text-calm font-outfit" htmlFor="crisis-region">
                  Crisis resources region
                </label>
                <select
                  id="crisis-region"
                  value={settings.crisis_region}
                  onChange={(event) => setSettings({ ...settings, crisis_region: event.target.value })}
                  className="w-full rounded-xl border border-slate-200 bg-white/50 px-4 py-3 text-slate-800 focus:outline-none focus:ring-2 focus:ring-calm/15 focus:border-calm transition-all duration-300 font-medium text-sm hover:border-slate-300 shadow-sm cursor-pointer"
                >
                  {['United States', 'Egypt', 'United Kingdom', 'Global'].map((option) => (
                    <option key={option} className="bg-white text-slate-800">{option}</option>
                  ))}
                </select>
              </div>

              <div className="grid gap-3 sm:grid-cols-2 pt-2">
                <label htmlFor="save-journal-history" className="flex items-center justify-between p-3.5 bg-white/40 border border-white/50 rounded-xl cursor-pointer hover:bg-white/70 hover:border-slate-300 transition-all duration-300 shadow-sm">
                  <div className="flex items-center gap-3">
                    <input
                      id="save-journal-history"
                      checked={settings.save_journal_history}
                      onChange={(event) => setSettings({ ...settings, save_journal_history: event.target.checked })}
                      type="checkbox"
                      className="rounded border-slate-300 text-calm focus:ring-calm/20 h-4.5 w-4.5 cursor-pointer"
                    />
                    <span className="text-sm font-semibold text-slate-700 font-outfit">Save journal history</span>
                  </div>
                </label>

                <label htmlFor="save-mood-history" className="flex items-center justify-between p-3.5 bg-white/40 border border-white/50 rounded-xl cursor-pointer hover:bg-white/70 hover:border-slate-300 transition-all duration-300 shadow-sm">
                  <div className="flex items-center gap-3">
                    <input
                      id="save-mood-history"
                      checked={settings.save_mood_history}
                      onChange={(event) => setSettings({ ...settings, save_mood_history: event.target.checked })}
                      type="checkbox"
                      className="rounded border-slate-300 text-calm focus:ring-calm/20 h-4.5 w-4.5 cursor-pointer"
                    />
                    <span className="text-sm font-semibold text-slate-700 font-outfit">Save mood history</span>
                  </div>
                </label>
              </div>
            </div>
          </Card>

          {/* Premium AI Provider Panel */}
          <Card title="AI & Inference Settings">
            <div className="space-y-4">
              <div className="flex items-center justify-between border-b border-slate-100 pb-4">
                <div>
                  <h4 className="font-bold text-ocean font-outfit text-base">Enable Real AI</h4>
                  <p className="text-xs text-slate-500 font-medium mt-0.5">Connect Bingo to live active model completion endpoints</p>
                </div>
                <label className="relative inline-flex items-center cursor-pointer">
                  <input
                    type="checkbox"
                    checked={settings.enable_real_ai}
                    onChange={(event) => setSettings({ ...settings, enable_real_ai: event.target.checked })}
                    className="sr-only peer"
                  />
                  <div className="w-11 h-6 bg-slate-200 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[2px] after:bg-white after:border-slate-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-calm"></div>
                </label>
              </div>

              {settings.enable_real_ai && (
                <div className="space-y-4 pt-2">
                  <div className="space-y-2">
                    <label className="block text-xs font-bold uppercase tracking-wider text-calm font-outfit" htmlFor="ai-provider">
                      AI Provider
                    </label>
                    <select
                      id="ai-provider"
                      value={settings.ai_provider}
                      onChange={(event) => setSettings({ ...settings, ai_provider: event.target.value })}
                      className="w-full rounded-xl border border-slate-200 bg-white/50 px-4 py-3 text-slate-800 focus:outline-none focus:ring-2 focus:ring-calm/15 focus:border-calm transition-all duration-300 font-medium text-sm hover:border-slate-300 shadow-sm cursor-pointer"
                    >
                      <option value="mock">Offline Simulator (Demo Mode)</option>
                      <option value="pollinations">Pollinations.ai (Keyless & Free)</option>
                      <option value="huggingface">Hugging Face Inference Hub</option>
                      <option value="openai">OpenAI Direct API</option>
                      <option value="openrouter">OpenRouter API</option>
                    </select>
                  </div>

                  {settings.ai_provider === 'pollinations' && (
                    <div className="rounded-xl bg-sky/15 border border-sky/35 p-4 text-xs text-slate-700 leading-relaxed shadow-sm">
                      <strong className="text-ocean block mb-1 font-outfit text-sm">Free & Keyless Completions</strong> 
                      Pollinations.ai provides free, direct completion responses for your mental wellness companion without requiring API keys or account setup.
                    </div>
                  )}

                  {settings.ai_provider === 'huggingface' && (
                    <div className="space-y-4 pt-3 border-t border-slate-100/80">
                      <div className="space-y-2">
                        <label className="block text-xs font-bold uppercase tracking-wider text-calm font-outfit" htmlFor="hf-token">
                          Hugging Face API Token
                        </label>
                        <div className="relative">
                          <input
                            id="hf-token"
                            type={showHFToken ? 'text' : 'password'}
                            value={settings.hf_token || ''}
                            onChange={(event) => setSettings({ ...settings, hf_token: event.target.value })}
                            placeholder="hf_..."
                            className="w-full rounded-xl border border-slate-200 bg-white/50 pl-4 pr-10 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-calm/15 focus:border-calm transition-all duration-300"
                          />
                          <button
                            type="button"
                            onClick={() => setShowHFToken(!showHFToken)}
                            className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600 focus:outline-none"
                          >
                            {showHFToken ? (
                              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="h-5 w-5">
                                <path strokeLinecap="round" strokeLinejoin="round" d="M3.98 8.223A10.477 10.477 0 0 0 1.934 12C3.226 16.338 7.244 19.5 12 19.5c.993 0 1.953-.138 2.863-.395M21 21l-3.486-3.486m0 0a9 9 0 0 1-12.802-12.802L3 3m15.357 15.357A9.003 9.003 0 0 0 12 4.5c-4.756 0-8.773 3.162-10.065 7.498a10.522 10.522 0 0 0 1.718 3.213m15.357 2.446L14.54 14.54m-1.157-1.157a3 3 0 1 1-4.243-4.243m4.242 4.242L9.88 9.88" />
                              </svg>
                            ) : (
                              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="h-5 w-5">
                                <path strokeLinecap="round" strokeLinejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" />
                                <path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                              </svg>
                            )}
                          </button>
                        </div>
                      </div>
                      <div className="space-y-2">
                        <label className="block text-xs font-bold uppercase tracking-wider text-calm font-outfit" htmlFor="hf-model">
                          Hugging Face Model ID
                        </label>
                        <input
                          id="hf-model"
                          type="text"
                          value={settings.hf_model || ''}
                          onChange={(event) => setSettings({ ...settings, hf_model: event.target.value })}
                          placeholder="e.g. meta-llama/Meta-Llama-3-8B-Instruct"
                          className="w-full rounded-xl border border-slate-200 bg-white/50 px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-calm/15 focus:border-calm transition-all duration-300"
                        />
                      </div>
                      <div className="space-y-2">
                        <label className="block text-xs font-bold uppercase tracking-wider text-calm font-outfit" htmlFor="hf-base-url">
                          Inference URL Override (Optional)
                        </label>
                        <input
                          id="hf-base-url"
                          type="text"
                          value={settings.hf_base_url || ''}
                          onChange={(event) => setSettings({ ...settings, hf_base_url: event.target.value })}
                          placeholder="Defaults to standard HF Hub Endpoint"
                          className="w-full rounded-xl border border-slate-200 bg-white/50 px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-calm/15 focus:border-calm transition-all duration-300"
                        />
                      </div>
                    </div>
                  )}

                  {settings.ai_provider === 'openai' && (
                    <div className="space-y-4 pt-3 border-t border-slate-100/80">
                      <div className="space-y-2">
                        <label className="block text-xs font-bold uppercase tracking-wider text-calm font-outfit" htmlFor="openai-key">
                          OpenAI API Key
                        </label>
                        <div className="relative">
                          <input
                            id="openai-key"
                            type={showOpenAIKey ? 'text' : 'password'}
                            value={settings.openai_api_key || ''}
                            onChange={(event) => setSettings({ ...settings, openai_api_key: event.target.value })}
                            placeholder="sk-..."
                            className="w-full rounded-xl border border-slate-200 bg-white/50 pl-4 pr-10 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-calm/15 focus:border-calm transition-all duration-300"
                          />
                          <button
                            type="button"
                            onClick={() => setShowOpenAIKey(!showOpenAIKey)}
                            className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600 focus:outline-none"
                          >
                            {showOpenAIKey ? (
                              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="h-5 w-5">
                                <path strokeLinecap="round" strokeLinejoin="round" d="M3.98 8.223A10.477 10.477 0 0 0 1.934 12C3.226 16.338 7.244 19.5 12 19.5c.993 0 1.953-.138 2.863-.395M21 21l-3.486-3.486m0 0a9 9 0 0 1-12.802-12.802L3 3m15.357 15.357A9.003 9.003 0 0 0 12 4.5c-4.756 0-8.773 3.162-10.065 7.498a10.522 10.522 0 0 0 1.718 3.213m15.357 2.446L14.54 14.54m-1.157-1.157a3 3 0 1 1-4.243-4.243m4.242 4.242L9.88 9.88" />
                              </svg>
                            ) : (
                              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="h-5 w-5">
                                <path strokeLinecap="round" strokeLinejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" />
                                <path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                              </svg>
                            )}
                          </button>
                        </div>
                      </div>
                      <div className="space-y-2">
                        <label className="block text-xs font-bold uppercase tracking-wider text-calm font-outfit" htmlFor="openai-model">
                          OpenAI Model
                        </label>
                        <input
                          id="openai-model"
                          type="text"
                          value={settings.openai_model || ''}
                          onChange={(event) => setSettings({ ...settings, openai_model: event.target.value })}
                          placeholder="gpt-4o-mini"
                          className="w-full rounded-xl border border-slate-200 bg-white/50 px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-calm/15 focus:border-calm transition-all duration-300"
                        />
                      </div>
                      <div className="space-y-2">
                        <label className="block text-xs font-bold uppercase tracking-wider text-calm font-outfit" htmlFor="openai-base-url">
                          API Base URL (Optional)
                        </label>
                        <input
                          id="openai-base-url"
                          type="text"
                          value={settings.openai_base_url || ''}
                          onChange={(event) => setSettings({ ...settings, openai_base_url: event.target.value })}
                          placeholder="Defaults to OpenAI Endpoint"
                          className="w-full rounded-xl border border-slate-200 bg-white/50 px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-calm/15 focus:border-calm transition-all duration-300"
                        />
                      </div>
                    </div>
                  )}

                  {settings.ai_provider === 'openrouter' && (
                    <div className="space-y-4 pt-3 border-t border-slate-100/80">
                      <div className="space-y-2">
                        <label className="block text-xs font-bold uppercase tracking-wider text-calm font-outfit" htmlFor="openrouter-key">
                          OpenRouter API Key
                        </label>
                        <div className="relative">
                          <input
                            id="openrouter-key"
                            type={showOpenRouterKey ? 'text' : 'password'}
                            value={settings.openrouter_api_key || ''}
                            onChange={(event) => setSettings({ ...settings, openrouter_api_key: event.target.value })}
                            placeholder="sk-or-..."
                            className="w-full rounded-xl border border-slate-200 bg-white/50 pl-4 pr-10 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-calm/15 focus:border-calm transition-all duration-300"
                          />
                          <button
                            type="button"
                            onClick={() => setShowOpenRouterKey(!showOpenRouterKey)}
                            className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600 focus:outline-none"
                          >
                            {showOpenRouterKey ? (
                              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="h-5 w-5">
                                <path strokeLinecap="round" strokeLinejoin="round" d="M3.98 8.223A10.477 10.477 0 0 0 1.934 12C3.226 16.338 7.244 19.5 12 19.5c.993 0 1.953-.138 2.863-.395M21 21l-3.486-3.486m0 0a9 9 0 0 1-12.802-12.802L3 3m15.357 15.357A9.003 9.003 0 0 0 12 4.5c-4.756 0-8.773 3.162-10.065 7.498a10.522 10.522 0 0 0 1.718 3.213m15.357 2.446L14.54 14.54m-1.157-1.157a3 3 0 1 1-4.243-4.243m4.242 4.242L9.88 9.88" />
                              </svg>
                            ) : (
                              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="h-5 w-5">
                                <path strokeLinecap="round" strokeLinejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" />
                                <path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                              </svg>
                            )}
                          </button>
                        </div>
                      </div>
                      <div className="space-y-2">
                        <label className="block text-xs font-bold uppercase tracking-wider text-calm font-outfit" htmlFor="openrouter-model">
                          OpenRouter Model
                        </label>
                        <input
                          id="openrouter-model"
                          type="text"
                          value={settings.openrouter_model || ''}
                          onChange={(event) => setSettings({ ...settings, openrouter_model: event.target.value })}
                          placeholder="openai/gpt-4o-mini"
                          className="w-full rounded-xl border border-slate-200 bg-white/50 px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-calm/15 focus:border-calm transition-all duration-300"
                        />
                      </div>
                      <div className="space-y-2">
                        <label className="block text-xs font-bold uppercase tracking-wider text-calm font-outfit" htmlFor="openrouter-base-url">
                          API Base URL
                        </label>
                        <input
                          id="openrouter-base-url"
                          type="text"
                          value={settings.openrouter_base_url || ''}
                          onChange={(event) => setSettings({ ...settings, openrouter_base_url: event.target.value })}
                          placeholder="https://openrouter.ai/api/v1"
                          className="w-full rounded-xl border border-slate-200 bg-white/50 px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-calm/15 focus:border-calm transition-all duration-300"
                        />
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          </Card>
        </div>

        {/* Right column - notices, safety, actions */}
        <div className="space-y-6">
          {/* Action Status and Controls */}
          <Card title="Account Actions">
            <div className="space-y-4">
              <div className="flex flex-col gap-2.5">
                <Button onClick={save} variant="primary" className="w-full justify-center">
                  Save settings
                </Button>
                {status.includes('log in') ? (
                  <Button onClick={startDemoSession} variant="secondary" className="w-full justify-center">
                    Demo login
                  </Button>
                ) : null}
                <Button onClick={downloadExport} variant="secondary" className="w-full justify-center">
                  Export data
                </Button>
                <div className="grid grid-cols-2 gap-2 mt-1">
                  <Button onClick={signOut} variant="ghost" className="w-full justify-center text-xs">
                    Log out
                  </Button>
                  <Button onClick={requestDelete} variant="ghost" className="w-full justify-center text-xs text-coral hover:text-coral/80">
                    Delete account
                  </Button>
                </div>
              </div>
              <div className="rounded-xl border border-slate-200/80 bg-white/40 p-4 transition-all duration-300">
                <div className="flex items-center gap-2 mb-1.5">
                  <span className="w-2.5 h-2.5 rounded-full bg-calm animate-pulse-subtle"></span>
                  <span className="text-xs font-bold uppercase tracking-wider text-slate-500 font-outfit">Status Console</span>
                </div>
                <p className="text-xs text-slate-700 font-semibold leading-relaxed">{status}</p>
              </div>
            </div>
          </Card>

          {/* Vercel Deployment Notice Card */}
          <Card className="border-t-4 border-t-calm" title="Production & Local Routing">
            <div className="space-y-4 text-xs leading-relaxed text-slate-600">
              <div className="bg-white/40 border border-white/60 p-3.5 rounded-xl space-y-1 shadow-sm">
                <span className="font-bold text-calm font-outfit uppercase tracking-wider block text-[10px]">Local Application</span>
                <p className="text-slate-700">
                  The local Bingo uvicorn server now automatically routes completions directly to the Hugging Face Inference API using your newly configured token!
                </p>
              </div>
              <div className="bg-white/40 border border-white/60 p-3.5 rounded-xl space-y-1 shadow-sm">
                <span className="font-bold text-calm font-outfit uppercase tracking-wider block text-[10px]">Production Application</span>
                <p className="text-slate-700">
                  For your live Vercel production deployment, simply log into your account, go to Settings (/settings), turn on Enable Real AI, select Hugging Face, enter your access token in the UI, and click Save settings. Your settings will be instantly saved to your production database!
                </p>
              </div>
            </div>
          </Card>

          {/* Safety Card */}
          <Card className="border-t-4 border-t-sky" title="Safety boundary">
            <p className="text-sm leading-relaxed text-slate-600">
              Bingo offers supportive reflection, not therapy, diagnosis, medication advice, or emergency care. Real AI providers remain gated until clinical, legal, and privacy reviews are complete.
            </p>
          </Card>
        </div>
      </div>
    </section>
  );
}
