'use client';

import { useEffect, useState } from 'react';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { deleteAccount, exportAccount, getSettings, logout, mockLogin, updateSettings } from '@/lib/api';
import type { UserSettings } from '@/types/settings';

const defaults: UserSettings = {
  preferred_language: 'English',
  response_style: 'balanced',
  crisis_region: 'United States',
  save_journal_history: true,
  save_mood_history: true,
};

export default function Page() {
  const [settings, setSettings] = useState<UserSettings>(defaults);
  const [status, setStatus] = useState('Loading saved settings...');

  useEffect(() => {
    async function load() {
      try {
        setSettings(await getSettings());
        setStatus('Settings loaded from persistent storage.');
      } catch {
        setStatus('Please log in or use demo login to load settings.');
      }
    }
    void load();
  }, []);

  async function startDemoSession() {
    try {
      const auth = await mockLogin();
      setSettings(await getSettings());
      setStatus('Demo login active. Settings loaded from persistent storage.');
    } catch {
      setStatus('Could not start demo login.');
    }
  }

  async function save() {
    try {
      setSettings(await updateSettings(settings));
      setStatus('Settings saved for the current user.');
    } catch {
      setStatus('Please log in or use demo login before saving settings.');
    }
  }

  async function downloadExport() {
    try {
      await exportAccount();
      setStatus('Account export generated by the backend.');
    } catch {
      setStatus('Please log in before exporting account data.');
    }
  }

  async function signOut() {
    await logout();
    setStatus('Logged out. Protected data is unavailable until you log in again.');
  }

  async function requestDelete() {
    try {
      await deleteAccount();
      setStatus('Account marked for deletion and login disabled.');
    } catch {
      setStatus('Please log in before deleting account data.');
    }
  }

  return <section className="grid gap-6 lg:grid-cols-[1.1fr_0.9fr]">
    <div className="space-y-5">
      <p className="text-sm font-semibold uppercase tracking-wide text-calm">Bingo</p>
      <h1 className="text-4xl font-bold text-ink">Settings</h1>
      <p className="max-w-2xl text-lg text-slate-700">Manage preferences, saved data choices, and regional safety resources.</p>
      <div className="grid gap-4">
        <Card title="Preferred language">
          <label className="mb-2 block text-sm font-semibold text-ocean" htmlFor="preferred-language">Preferred language</label>
          <select id="preferred-language" value={settings.preferred_language} onChange={(event) => setSettings({ ...settings, preferred_language: event.target.value })} className="w-full rounded-lg border border-sky px-4 py-3">
            {['English', 'Arabic', 'Both'].map((option) => <option key={option}>{option}</option>)}
          </select>
        </Card>
        <Card title="Response style">
          <label className="mb-2 block text-sm font-semibold text-ocean" htmlFor="response-style">Response style</label>
          <select id="response-style" value={settings.response_style} onChange={(event) => setSettings({ ...settings, response_style: event.target.value })} className="w-full rounded-lg border border-sky px-4 py-3">
            {['short', 'balanced', 'detailed'].map((option) => <option key={option}>{option}</option>)}
          </select>
        </Card>
        <Card title="Crisis resources region">
          <label className="mb-2 block text-sm font-semibold text-ocean" htmlFor="crisis-region">Crisis resources region</label>
          <select id="crisis-region" value={settings.crisis_region} onChange={(event) => setSettings({ ...settings, crisis_region: event.target.value })} className="w-full rounded-lg border border-sky px-4 py-3">
            {['United States', 'Egypt', 'United Kingdom', 'Global'].map((option) => <option key={option}>{option}</option>)}
          </select>
        </Card>
        <Card title="Data privacy">
          <label className="flex items-center gap-3"><input checked={settings.save_journal_history} onChange={(event) => setSettings({ ...settings, save_journal_history: event.target.checked })} type="checkbox" /> Save journal history</label>
          <label className="mt-3 flex items-center gap-3"><input checked={settings.save_mood_history} onChange={(event) => setSettings({ ...settings, save_mood_history: event.target.checked })} type="checkbox" /> Save mood history</label>
        </Card>
      </div>
      <div className="flex flex-wrap items-center gap-3">
        {status.includes('log in') ? <Button onClick={startDemoSession} variant="secondary">Demo login</Button> : null}
        <Button onClick={save}>Save settings</Button>
        <Button onClick={downloadExport} variant="secondary">Export data</Button>
        <Button onClick={signOut} variant="ghost">Log out</Button>
        <Button onClick={requestDelete} variant="ghost">Delete account</Button>
        <p className="text-sm text-slate-600">{status}</p>
      </div>
    </div>
    <Card title="Safety boundary">
      <p>Bingo offers supportive reflection, not therapy, diagnosis, medication advice, or emergency care. Real AI providers remain gated until clinical, legal, and privacy reviews are complete.</p>
    </Card>
  </section>;
}
